/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package possystem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import static java.time.Clock.system;
import javax.swing.JOptionPane;

/**
 *
 * @author James Flond
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Double basep;
    double cheesep = 0;
    double cheeset;
    double baconp = 0;
    double bacont =0;
    double mealp = 0;
    double mealt = 0;
    double extrap;
    double itemp;
    double qty = 1;
    String text = "1";
    String addOrder = "\n";
    double total;
    double totalp;
    public GUI() {
        initComponents();
  
    ButtonHandler handler = new ButtonHandler();
    
    jRadioButton1.addActionListener(handler);
    jRadioButton2.addActionListener(handler);
    jCheckBox1.addActionListener(handler);
    jCheckBox2.addActionListener(handler);
    jCheckBox4.addActionListener(handler);
    textField1.addActionListener(handler);
    
    MenuHandler m = new MenuHandler();
    jMenuItem1.addActionListener(m);
    jMenuItem2.addActionListener(m);
    jMenuItem3.addActionListener(m);
    jMenuItem4.addActionListener(m);

  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        textArea2 = new java.awt.TextArea();
        textField1 = new java.awt.TextField();
        textArea3 = new java.awt.TextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Single Burger");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Double Burger");
        jRadioButton2.setToolTipText("");

        label1.setText("Order");

        label2.setText("Item Price");

        label3.setText("Quantity");

        label4.setText("Order Total");

        textArea1.setColumns(20);
        textArea1.setEditable(false);
        textArea1.setRows(30);

        textField1.setText("1");

        jCheckBox1.setText("add cheese");

        jCheckBox2.setText("add bacon");

        jCheckBox4.setText("make into meal");

        jMenu1.setText("File");

        jMenuItem4.setText("Exit");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Order");

        jMenuItem1.setText("Add to Order");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Clear for next item");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("New Order");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox4))
                        .addGap(179, 179, 179)
                        .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(33, 33, 33)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addGap(29, 29, 29)
                        .addComponent(jCheckBox4)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        label3.getAccessibleContext().setAccessibleName("Quantity");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    private java.awt.TextArea textArea3;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
 
    // Create private inner class to hadnle ItemListener or ActionListener

    //Action Handler for checkbox and radiobuttons
    private class ButtonHandler implements ActionListener
{
	@Override
	public void actionPerformed(ActionEvent e)
	{
            processChoices();
	}
}
    private void processChoices()
    {
        //read burger size 
                if (jRadioButton1.isSelected())
                {      
            textArea1.setText(addOrder+ "\n"+"Single Burger   3.50\n");
              basep = 3.5 ;
            
                }
        else if (jRadioButton2.isSelected())
        {textArea1.setText(addOrder+ "\n"+"Double Burger   4.75\n");
        basep = 4.75;}
                else
        {
            JOptionPane.showMessageDialog(null,"Must select a burger size.","Error", JOptionPane.ERROR_MESSAGE);
            return; //
        }
                
                if(jCheckBox4.isSelected() == true)
                {
            textArea1.append("\nmeal   4.00");
            mealp = 4;
            
               }
                else if(jCheckBox4.isSelected() == false)
                {
                mealp = 0;
                
                }
            if(jCheckBox1.isSelected())
            {
                textArea1.append("\nadd cheese   .50");
                cheesep = .5;
            }
            else if(jCheckBox1.isSelected() == false)
            {
                cheesep = 0;
            }
            if(jCheckBox2.isSelected())
            {
                textArea1.append("\nadd bacon   1.25");
            baconp = 1.25;
            }
            else if (jCheckBox2.isSelected() == false)
            {
                baconp = 0;
            }
            if (textField1 == null)
            {
                            
                    text  = "1";
           
            }
            else 
            {
                text= textField1.getText();
            }
             qty = Double.parseDouble(text);
            mealt = 0 + mealp;
            cheeset = 0 + cheesep;
            bacont = 0 + baconp;
            extrap = mealt + cheeset + bacont ;
            itemp = qty *(extrap + basep);
            
            total = totalp + itemp;
                   
                   textArea2.setText(String.valueOf(itemp));
                   textArea3.setText(String.valueOf(total));
        
    }
    private class MenuHandler implements ActionListener
{
	@Override
	public void actionPerformed(ActionEvent e)
	{
		
		if(e.getSource()== jMenuItem1)
                {
                    
              addOrder = textArea1.getText() ;
                buttonGroup1.clearSelection();
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox4.setSelected(false);
                textField1.setText("1");
                
                 totalp += itemp;
               
                
               
                }
		else if (e.getSource() == jMenuItem2)
                {
                buttonGroup1.clearSelection();
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox4.setSelected(false);
                textField1.setText("1");
                }
                else if(e.getSource()== jMenuItem3)
                {
                buttonGroup1.clearSelection();
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox4.setSelected(false);
                textArea1.setText(null);
                 textField1.setText("1");
                
                }
                else if(e.getSource() == jMenuItem4)
                    System.exit(0)
                    ;
	}
}
    
    //Connect Radio Buttons to ItemListener and create ItemListener Object
   
}
